apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-ptvv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-ptvv@sha256:a7792ecf4cc0e9bdb052e90102076b5a4fea2000344d0dad62a0e2eaac0ce9c2
        name: container-image
        resources: {}
status: {}
