apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-hylu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-hylu@sha256:4e1269ec2a54b0f6ee8a9a289f60bd833478cda31fcf63a4552e9a88e9440b72
        name: my-nodejs
        resources: {}
status: {}
